{% set version = "1.4.0" %}

package:
  name: ipydatagrid
  version: {{ version }}

source:
  url: https://github.com/bloomberg/ipydatagrid/archive/{{ version }}.tar.gz
  sha256: 30cd9d2394d5dda1a30a1ad7343ecc249e4ad4aa8a515c8401cc3ee09329ee30

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - hatch-jupyter-builder >=0.8.1
    - hatchling
    - jupyterlab >=4.0.5
    - pip
    - python >=3.8
    - yarn ==3.*
  run:
    - bqplot >=0.11.6
    - ipywidgets >=7.6,<9
    - pandas >=1.3.5
    - py2vega >=0.5
    - python >=3.8

test:
  imports:
    - ipydatagrid
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>lab_extensions 2>&1
    - grep -iE "ipydatagrid.*{{ version.replace(".", "\\.") }}.*OK" lab_extensions
  requires:
    - jupyterlab >=3,<4
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/bloomberg/ipydatagrid
  summary: Fast Datagrid widget for the Jupyter Notebook and JupyterLab
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - ipydatagrid/labextension/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - bollwyvl
    - ibdafna
    - kaiayoung
    - martinRenou
