{% set name = "ipydatagrid" %}
{% set version = "1.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a452d5d72e81301a7ff1ce8daa55ef626a720c144e1f8b620ca059760542a9dc

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -c "import shutil as s, os; s.rmtree('examples'); os.unlink('pyproject.toml')"
    - {{ PYTHON }} -m pip install --install-option="--skip-npm" . -vv

requirements:
  host:
    - jupyter-packaging
    - pip
    - python >=3.6
  run:
    - bqplot >=0.11.6
    - ipywidgets >=7.6.0,<8
    - pandas >=0.25.0
    - py2vega >=0.5.0
    - python >=3.6

test:
  imports:
    - ipydatagrid
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>lab_extensions 2>&1  # [unix]
    - cat lab_extensions | grep "ipydatagrid.*{{ version.replace(".", "\\.") }}.*OK"  # [unix]
  requires:
    - pip
    - jupyterlab >=3,<4

about:
  home: https://github.com/bloomberg/ipydatagrid
  summary: Fast Datagrid widget for the Jupyter Notebook and JupyterLab
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
    - ibdafna
    - kaiayoung
