{% set version = "1.2.0" %}

package:
  name: ipydatagrid
  version: {{ version }}

source:
  url: https://github.com/bloomberg/ipydatagrid/archive/{{ version }}.tar.gz
  sha256: 3df145e3f789a28789a2281da9656a1fd3759d336814859f7b29462bbe0916fd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - hatch-jupyter-builder >=0.8.1
    - hatchling
    - jupyterlab >=4,<5
    - pip
    - python >=3.7
    - yarn =3
  run:
    - bqplot >=0.11.6
    - ipywidgets >=7.6.0,<9
    - pandas
    - py2vega >=0.5.0
    - python >=3.7

test:
  imports:
    - ipydatagrid
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>lab_extensions 2>&1
    - grep -iE "ipydatagrid.*{{ version.replace(".", "\\.") }}.*OK" lab_extensions
  requires:
    - jupyterlab >=3,<4
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/bloomberg/ipydatagrid
  summary: Fast Datagrid widget for the Jupyter Notebook and JupyterLab
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - ipydatagrid/labextension/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - bollwyvl
    - ibdafna
    - kaiayoung
    - martinRenou
