{% set version = "1.1.13" %}

package:
  name: ipydatagrid
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipydatagrid/ipydatagrid-{{ version }}.tar.gz
  sha256: a051950410c63b5d60d15645bd5b574c3c0623dd1709ab61b72dbcecfb9d66ac

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - bqplot >=0.11.6
    - ipywidgets >=7.6.0,<9
    - pandas
    - py2vega >=0.5.0
    - python >=3.7

test:
  imports:
    - ipydatagrid
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>lab_extensions 2>&1
    - grep -iE "ipydatagrid.*{{ version.replace(".", "\\.") }}.*OK" lab_extensions
  requires:
    - jupyterlab >=3,<4
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/bloomberg/ipydatagrid
  summary: Fast Datagrid widget for the Jupyter Notebook and JupyterLab
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
    - ibdafna
    - kaiayoung
