{% set version = "1.1.15" %}

package:
  name: ipydatagrid
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipydatagrid/ipydatagrid-{{ version }}.tar.gz
  sha256: 4b4da0bf2af03599ae52f5a04d05595c230917a03883b43aa176616979070b53

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - hatch-jupyter-builder >=0.8.1
    - hatchling
    - jupyterlab >=3,<4
    - pip
    - python >=3.7
    - yarn <2
  run:
    - bqplot >=0.11.6
    - ipywidgets >=7.6.0,<9
    - pandas
    - py2vega >=0.5.0
    - python >=3.7

test:
  imports:
    - ipydatagrid
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>lab_extensions 2>&1
    - grep -iE "ipydatagrid.*{{ version.replace(".", "\\.") }}.*OK" lab_extensions
  requires:
    - jupyterlab >=3,<4
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/bloomberg/ipydatagrid
  summary: Fast Datagrid widget for the Jupyter Notebook and JupyterLab
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - ipydatagrid/labextension/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - bollwyvl
    - ibdafna
    - kaiayoung
